# **Python Task **

# **4.1 Exercise on Functions**

**Task 1: Unit Conversion Program**

In [ ]:
def convert_length(value, direction):
    """
    Convert between meters and feet.

    Parameters:
        value (float): The value to convert
        direction (str): Either 'm_to_ft' or 'ft_to_m'

    Returns:
        float: The converted value
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value * 0.3048
    else:
        raise ValueError("Invalid direction for length conversion")

def convert_weight(value, direction):
    """
    Convert between kilograms and pounds.

    Parameters:
        value (float): The value to convert
        direction (str): Either 'kg_to_lb' or 'lb_to_kg'

    Returns:
        float: The converted value
    """
    if direction == 'kg_to_lb':
        return value * 2.20462
    elif direction == 'lb_to_kg':
        return value * 0.453592
    else:
        raise ValueError("Invalid direction for weight conversion")

def convert_volume(value, direction):
    """
    Convert between liters and gallons.

    Parameters:
        value (float): The value to convert
        direction (str): Either 'l_to_gal' or 'gal_to_l'

    Returns:
        float: The converted value
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value * 3.78541
    else:
        raise ValueError("Invalid direction for volume conversion")

def main():
    print("Unit Conversion Program")
    print("1. Length Conversion")
    print("2. Weight Conversion")
    print("3. Volume Conversion")

    try:
        conversion_type = int(input("Choose conversion type (1-3): "))

        if conversion_type == 1:
            print("\nLength Conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            direction = int(input("Choose direction (1-2): "))

            value = float(input("Enter value to convert: "))

            if direction == 1:
                result = convert_length(value, 'm_to_ft')
                print(f"{value} meters = {result:.2f} feet")
            elif direction == 2:
                result = convert_length(value, 'ft_to_m')
                print(f"{value} feet = {result:.2f} meters")
            else:
                print("Invalid direction choice!")

        elif conversion_type == 2:
            print("\nWeight Conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            direction = int(input("Choose direction (1-2): "))

            value = float(input("Enter value to convert: "))

            if direction == 1:
                result = convert_weight(value, 'kg_to_lb')
                print(f"{value} kilograms = {result:.2f} pounds")
            elif direction == 2:
                result = convert_weight(value, 'lb_to_kg')
                print(f"{value} pounds = {result:.2f} kilograms")
            else:
                print("Invalid direction choice!")

        elif conversion_type == 3:
            print("\nVolume Conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            direction = int(input("Choose direction (1-2): "))

            value = float(input("Enter value to convert: "))

            if direction == 1:
                result = convert_volume(value, 'l_to_gal')
                print(f"{value} liters = {result:.2f} gallons")
            elif direction == 2:
                result = convert_volume(value, 'gal_to_l')
                print(f"{value} gallons = {result:.2f} liters")
            else:
                print("Invalid direction choice!")

        else:
            print("Invalid conversion type!")

    except ValueError as e:
        if str(e).startswith("Invalid direction"):
            print(e)
        else:
            print("Invalid input! Please enter a number.")

if __name__ == "__main__":
    main()

Unit Conversion Program
1. Length Conversion
2. Weight Conversion
3. Volume Conversion
Choose conversion type (1-3): 2

Weight Conversion:
1. Kilograms to Pounds
2. Pounds to Kilograms
Choose direction (1-2): 1
Enter value to convert: 45
45.0 kilograms = 99.21 pounds


**Task 2: Mathematical Operations on a List**

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numbers

    Returns:
        float: The sum of the numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
        numbers (list): A list of numbers

    Returns:
        float: The average of the numbers
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numbers

    Returns:
        float: The maximum value
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list")
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numbers

    Returns:
        float: The minimum value
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list")
    return min(numbers)

def main():
    print("Mathematical Operations on a List")
    print("1. Calculate Sum")
    print("2. Calculate Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        operation = int(input("Choose operation (1-4): "))

        input_string = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(x) for x in input_string.split()]

        if not numbers:
            print("Error: Empty list provided")
            return

        if operation == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif operation == 2:
            result = calculate_average(numbers)
            print(f"Average: {result:.2f}")
        elif operation == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif operation == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid operation choice!")

    except ValueError as e:
        if str(e).startswith("Cannot"):
            print(f"Error: {e}")
        else:
            print("Invalid input! Please enter valid numbers.")

if __name__ == "__main__":
    main()

Mathematical Operations on a List
1. Calculate Sum
2. Calculate Average
3. Find Maximum
4. Find Minimum
Choose operation (1-4): 3
Enter a list of numbers separated by spaces: 2 4 5 6 8 1
Maximum: 8.0


# **4.2 Exercise on List Manipulation**

**1. Extract Every Other Element**

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
        lst (list): The input list

    Returns:
        list: A new list containing every other element
    """
    return lst[::2]

# Test the function
test_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(test_list)
print(f"Original list: {test_list}")
print(f"Every other element: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


**2. Slice a Sublist**

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, from start to end (inclusive).

    Parameters:
        lst (list): The input list
        start (int): The starting index
        end (int): The ending index (inclusive)

    Returns:
        list: The sublist from start to end (inclusive)
    """
    return lst[start:end+1]

# Test the function
test_list = [1, 2, 3, 4, 5, 6]
start_idx = 2
end_idx = 4
result = get_sublist(test_list, start_idx, end_idx)
print(f"Original list: {test_list}")
print(f"Sublist from index {start_idx} to {end_idx}: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


**3. Reverse a List Using Slicing**

In [ ]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): The input list

    Returns:
        list: The reversed list
    """
    return lst[::-1]

# Test the function
test_list = [1, 2, 3, 4, 5]
result = reverse_list(test_list)
print(f"Original list: {test_list}")
print(f"Reversed list: {result}")

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


**4. Remove the First and Last Elements**

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
        lst (list): The input list

    Returns:
        list: A new list without the first and last elements
    """
    return lst[1:-1]

# Test the function
test_list = [1, 2, 3, 4, 5]
result = remove_first_last(test_list)
print(f"Original list: {test_list}")
print(f"List without first and last elements: {result}")

Original list: [1, 2, 3, 4, 5]
List without first and last elements: [2, 3, 4]


**5. Get the First n Elements**

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
        lst (list): The input list
        n (int): Number of elements to extract

    Returns:
        list: A new list containing the first n elements
    """
    return lst[:n]

# Test the function
test_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(test_list, n)
print(f"Original list: {test_list}")
print(f"First {n} elements: {result}")

Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


**6. Extract Elements from the End**

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list using slicing.

    Parameters:
        lst (list): The input list
        n (int): Number of elements to extract from the end

    Returns:
        list: A new list containing the last n elements
    """
    return lst[-n:]

# Test the function
test_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(test_list, n)
print(f"Original list: {test_list}")
print(f"Last {n} elements: {result}")

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


**7. Extract Elements in Reverse Order**

In [ ]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order starting from the second-to-last element
    and skipping one element in between.

    Parameters:
        lst (list): The input list

    Returns:
        list: A new list with every second element starting from the second-to-last
    """
    return lst[-2::-2]

# Test the function
test_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(test_list)
print(f"Original list: {test_list}")
print(f"Reverse skip: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Reverse skip: [5, 3, 1]


# **4.3 Exercise on Nested List**

**1. Flatten a Nested List**

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list

    Returns:
        list: A flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

# Test the function
test_list = [[1, 2], [3, 4], [5]]
result = flatten(test_list)
print(f"Nested list: {test_list}")
print(f"Flattened list: {result}")

Nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


**2. Accessing Nested List Elements**

In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
        lst (list): A nested list
        indices (list): A list of indices to navigate through the nested list

    Returns:
        Any: The element at the specified position
    """
    current = lst
    for idx in indices:
        current = current[idx]
    return current

# Test the function
test_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(test_list, indices)
print(f"Nested list: {test_list}")
print(f"Element at indices {indices}: {result}")

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


**3. Sum of All Elements in a Nested List**

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list (regardless of depth).

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: The sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Test the function
test_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(test_list)
print(f"Nested list: {test_list}")
print(f"Sum: {result}")

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum: 21


**4. Remove Specific Element from a Nested List**

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list
        elem: The element to remove

    Returns:
        list: The modified list with elem removed
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

# Test the function
test_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(test_list, elem)
print(f"Original nested list: {test_list}")
print(f"After removing {elem}: {result}")

Original nested list: [[1, 2], [3, 2], [4, 5]]
After removing 2: [[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List**

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list (regardless of depth).

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: The maximum element
    """
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_item = find_max(item)
            if max_item > max_value:
                max_value = max_item
        elif item > max_value:
            max_value = item
    return max_value

# Test the function
test_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(test_list)
print(f"Nested list: {test_list}")
print(f"Maximum element: {result}")

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


**6. Count Occurrences of an Element in a Nested List**

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): A nested list
        elem: The element to count

    Returns:
        int: The number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Test the function
test_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(test_list, elem)
print(f"Nested list: {test_list}")
print(f"Occurrences of {elem}: {result}")

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


**7. Flatten a List of Lists of Lists**

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
        lst (list): A deeply nested list

    Returns:
        list: A single flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Test the function
test_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(test_list)
print(f"Deeply nested list: {test_list}")
print(f"Flattened list: {result}")

Deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average**

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers

    Returns:
        float: The average of all elements
    """
    flat_list = deep_flatten(lst)
    if not flat_list:
        raise ValueError("Cannot calculate average of an empty list")
    return sum(flat_list) / len(flat_list)

def deep_flatten(lst):
    """
    Helper function to flatten a deeply nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Test the function
test_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(test_list)
print(f"Nested list: {test_list}")
print(f"Average: {result}")

Nested list: [[1, 2], [3, 4], [5, 6]]
Average: 3.5


# **NumPy Task **

# **10.1 Basic Vector and Matrix Operation with NumPy**

**Problem 1: Array Creation**

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array with size 2x2:")
print(empty_array)
print()

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("All ones array with size 4x2:")
print(ones_array)
print()

# 3. Return a new array of given shape and type, filled with fill value
fill_array = np.full((3, 3), 7)  # 3x3 array filled with 7s
print("Array filled with 7s:")
print(fill_array)
print()

# 4. Return a new array of zeros with same shape and type as a given array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(sample_array)
print("Original array:")
print(sample_array)
print("Zeros array with same shape:")
print(zeros_like_array)
print()

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("Ones array with same shape:")
print(ones_like_array)
print()

# 6. Convert existing list to numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("Original list:", new_list)
print("NumPy array:", np_array)
print("Type:", type(np_array))

Empty array with size 2x2:
[[2.85375978e-316 0.00000000e+000]
 [1.63321133e-301 1.76145531e-312]]

All ones array with size 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Original array:
[[1 2 3]
 [4 5 6]]
Zeros array with same shape:
[[0 0 0]
 [0 0 0]]

Ones array with same shape:
[[1 1 1]
 [1 1 1]]

Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


**Problem 2: Array Manipulation: Numerical Ranges and Array Indexing**

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(range_array)
print()

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:")
print(matrix_3x3)
print()

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:")
print(identity_matrix)
print()

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
array_mean = random_array.mean()
print("Random array of size 30:")
print(random_array)
print(f"Mean of the array: {array_mean}")
print()

# 5. Create a 10x10 array with random values and find min and max values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 random array created")
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")
print()

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("Zero array with 5th element = 1:")
print(zero_array)
print()

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)
print()

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:")
print(border_array)
print()

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:")
print(checkerboard)

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.18214518 0.35920057 0.38436508 0.94245458 0.31999875 0.43671131
 0.48004829 0.15230226 0.74385035 0.20704004 0.62889791 0.93548788
 0.33997351 0.59369017 0.57854405 0.70905039 0.10788435 0.73832252
 0.50679423 0.03914931 0.76653742 0.85025165 0.33292748 0.78528045
 0.61200092 0.73944525 0.43854206 0.7657157  0.34248402 0.47950778]
Mean of the array: 0.5166201161678463

10x10 random array created
Minimum value: 0.00839072212123626
Maximum value: 0.996281154982201

Zero array with 5th element = 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [

**Problem 3: Array Operations**

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x =")
print(x)
print("\ny =")
print(y)
print("\nv =", v)
print("w =", w)
print()

# 1. Add the two arrays
sum_xy = x + y
print("1. x + y =")
print(sum_xy)
print()

# 2. Subtract the two arrays
diff_xy = x - y
print("2. x - y =")
print(diff_xy)
print()

# 3. Multiply the array with any integer of your choice
scalar_mul = x * 3
print("3. x * 3 =")
print(scalar_mul)
print()

# 4. Find the square of each element of the array
squared_x = x ** 2
print("4. x^2 =")
print(squared_x)
print()

# 5. Find dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("5. Dot products:")
print(f"v · w = {dot_vw}")
print(f"x · v =")
print(dot_xv)
print(f"x · y =")
print(dot_xy)
print()

# 6. Concatenate arrays
# Along rows
concat_rows = np.concatenate((x, y), axis=0)  # or np.vstack((x, y))
print("6a. Concatenate x and y along rows:")
print(concat_rows)
print()

# Along columns for v and w (need to reshape first)
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_cols = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("6b. Concatenate v and w along columns:")
print(concat_cols)
print()

# 7. Try to concatenate x and v (will cause error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("7. Concatenate x and v:")
    print(concat_xv)
except ValueError as e:
    print("7. Error when concatenating x and v:")
    print(str(e))
    print("Explanation: The arrays have different shapes and cannot be concatenated directly.")
    print("x has shape", x.shape, "while v has shape", v.shape)
    print("To concatenate, v would need to be reshaped to have the same number of columns as x.")

x =
[[1 2]
 [3 5]]

y =
[[5 6]
 [7 8]]

v = [ 9 10]
w = [11 12]

1. x + y =
[[ 6  8]
 [10 13]]

2. x - y =
[[-4 -4]
 [-4 -3]]

3. x * 3 =
[[ 3  6]
 [ 9 15]]

4. x^2 =
[[ 1  4]
 [ 9 25]]

5. Dot products:
v · w = 219
x · v =
[29 77]
x · y =
[[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The arrays have different shapes and cannot be concatenated directly.
x has shape (2, 2) while v has shape (2,)
To concatenate, v would need to be reshaped to have the same number of columns as x.


**Problem 4: Matrix Operations**

In [ ]:
import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A =")
print(A)
print("\nB =")
print(B)
print()

# 1. Prove A.A^(-1) = I
# Calculate inverse of A
A_inv = np.linalg.inv(A)
print("1. A^(-1) =")
print(A_inv)

# Calculate A.A^(-1)
A_times_A_inv = np.dot(A, A_inv)
print("A.A^(-1) =")
print(A_times_A_inv)
print("This is approximately equal to the identity matrix I, with small floating-point errors.")
print()

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB =")
print(AB)
print("BA =")
print(BA)
print("As we can see, AB ≠ BA.")
print()

# 3. Prove (AB)^T = B^T.A^T
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)
print("3. (AB)^T =")
print(AB_T)
print("B^T.A^T =")
print(B_T_A_T)
print("As we can see, (AB)^T = B^T.A^T.")
print()

# Solving the system of linear equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix representation: AX = B
A_sys = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

print("4. System of equations in matrix form:")
print("A =")
print(A_sys)
print("B =", B_sys)

# Solve using inverse methods
A_sys_inv = np.linalg.inv(A_sys)
X = np.dot(A_sys_inv, B_sys)

print("\nSolution using inverse method:")
print(f"X = {X}")
print(f"Therefore: x = {X[0]}, y = {X[1]}, z = {X[2]}")

# Solve using np.linalg.solve
X_linalg = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:")
print(f"X = {X_linalg}")
print(f"Therefore: x = {X_linalg[0]}, y = {X_linalg[1]}, z = {X_linalg[2]}")

# Verify the solution
verification = np.dot(A_sys, X_linalg)
print("\nVerification: A.X =", verification)
print("Original B =", B_sys)
print("The solution is correct as A.X = B.")

A =
[[3 4]
 [7 8]]

B =
[[5 3]
 [2 1]]

1. A^(-1) =
[[-2.    1.  ]
 [ 1.75 -0.75]]
A.A^(-1) =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
This is approximately equal to the identity matrix I, with small floating-point errors.

2. AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
As we can see, AB ≠ BA.

3. (AB)^T =
[[23 51]
 [13 29]]
B^T.A^T =
[[23 51]
 [13 29]]
As we can see, (AB)^T = B^T.A^T.

4. System of equations in matrix form:
A =
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B = [-1 -3  9]

Solution using inverse method:
X = [ 2.  1. -2.]
Therefore: x = 2.0, y = 1.0, z = -2.0

Solution using np.linalg.solve:
X = [ 2.  1. -2.]
Therefore: x = 2.0, y = 1.0000000000000002, z = -2.0

Verification: A.X = [-1. -3.  9.]
Original B = [-1 -3  9]
The solution is correct as A.X = B.


**10.2 Experiment: How Fast is NumPy?**

In [ ]:
import numpy as np
import time
import random

# Function to measure execution time
def measure_time(func):
    start_time = time.time()
    result = func()
    end_time = time.time()
    return end_time - start_time, result

# 1. Element-wise Addition
print("1. Element-wise Addition:")

# Create data
size = 1000000
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]
array1 = np.array(list1)
array2 = np.array(list2)

# Using Python lists
def list_addition():
    result = [a + b for a, b in zip(list1, list2)]
    return result

time_list_add, _ = measure_time(list_addition)
print(f"   Time taken with Python lists: {time_list_add:.6f} seconds")

# Using NumPy arrays
def numpy_addition():
    result = array1 + array2
    return result

time_numpy_add, _ = measure_time(numpy_addition)
print(f"   Time taken with NumPy arrays: {time_numpy_add:.6f} seconds")
print(f"   Speed improvement: {time_list_add / time_numpy_add:.2f}x")
print()

# 2. Element-wise Multiplication
print("2. Element-wise Multiplication:")

# Using Python lists
def list_multiplication():
    result = [a * b for a, b in zip(list1, list2)]
    return result

time_list_mul, _ = measure_time(list_multiplication)
print(f"   Time taken with Python lists: {time_list_mul:.6f} seconds")

# Using NumPy arrays
def numpy_multiplication():
    result = array1 * array2
    return result

time_numpy_mul, _ = measure_time(numpy_multiplication)
print(f"   Time taken with NumPy arrays: {time_numpy_mul:.6f} seconds")
print(f"   Speed improvement: {time_list_mul / time_numpy_mul:.2f}x")
print()

# 3. Dot Product
print("3. Dot Product:")

# Using Python lists
def list_dot_product():
    result = sum(a * b for a, b in zip(list1, list2))
    return result

time_list_dot, _ = measure_time(list_dot_product)
print(f"   Time taken with Python lists: {time_list_dot:.6f} seconds")

# Using NumPy arrays
def numpy_dot_product():
    result = np.dot(array1, array2)
    return result

time_numpy_dot, _ = measure_time(numpy_dot_product)
print(f"   Time taken with NumPy arrays: {time_numpy_dot:.6f} seconds")
print(f"   Speed improvement: {time_list_dot / time_numpy_dot:.2f}x")
print()

# 4. Matrix Multiplication
# Note: Using smaller matrices for Python list implementation due to performance constraints
print("4. Matrix Multiplication:")
print("   Note: Using 100x100 matrices instead of 1000x1000 for Python lists due to performance constraints")

# Create data (smaller size for lists)
small_size = 100
list_matrix1 = [[random.random() for _ in range(small_size)] for _ in range(small_size)]
list_matrix2 = [[random.random() for _ in range(small_size)] for _ in range(small_size)]

# Using Python lists
def list_matrix_multiplication():
    result = [[0 for _ in range(small_size)] for _ in range(small_size)]
    for i in range(small_size):
        for j in range(small_size):
            for k in range(small_size):
                result[i][j] += list_matrix1[i][k] * list_matrix2[k][j]
    return result

time_list_matmul, _ = measure_time(list_matrix_multiplication)
print(f"   Time taken with Python lists (100x100): {time_list_matmul:.6f} seconds")

# For NumPy, let's use the full size
full_size = 1000
np_matrix1 = np.random.random((full_size, full_size))
np_matrix2 = np.random.random((full_size, full_size))

# Using NumPy arrays
def numpy_matrix_multiplication():
    result = np.dot(np_matrix1, np_matrix2)
    return result

time_numpy_matmul, _ = measure_time(numpy_matrix_multiplication)
print(f"   Time taken with NumPy arrays (1000x1000): {time_numpy_matmul:.6f} seconds")
print(f"   Note: The NumPy implementation is handling a much larger matrix size.")

# Estimate comparison for equal-sized matrices
estimated_list_time = time_list_matmul * (1000/100)**3  # O(n^3) complexity
print(f"   Estimated time for Python lists with 1000x1000 matrices: {estimated_list_time:.2f} seconds")
print(f"   Estimated speed improvement: {estimated_list_time / time_numpy_matmul:.2f}x")

1. Element-wise Addition:
   Time taken with Python lists: 0.399987 seconds
   Time taken with NumPy arrays: 0.021666 seconds
   Speed improvement: 18.46x

2. Element-wise Multiplication:
   Time taken with Python lists: 0.214967 seconds
   Time taken with NumPy arrays: 0.004698 seconds
   Speed improvement: 45.76x

3. Dot Product:
   Time taken with Python lists: 0.136868 seconds
   Time taken with NumPy arrays: 0.009033 seconds
   Speed improvement: 15.15x

4. Matrix Multiplication:
   Note: Using 100x100 matrices instead of 1000x1000 for Python lists due to performance constraints
   Time taken with Python lists (100x100): 0.509091 seconds
   Time taken with NumPy arrays (1000x1000): 0.059876 seconds
   Note: The NumPy implementation is handling a much larger matrix size.
   Estimated time for Python lists with 1000x1000 matrices: 509.09 seconds
   Estimated speed improvement: 8502.39x
